# Generated by Django 3.0.6 on 2020-05-17 17:31

from django.db import migrations

def create_default_tree(apps, schema_editor):
    Tree = apps.get_model('tags', 'Tree')

    tree = Tree(name="Tree")
    tree.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tree'),
    ]

    operations = [
            migrations.RunPython(create_default_tree),
    ]
