# Generated by Django 3.0.6 on 2020-05-17 17:31

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tree'),
    ]

    operations = [
    ]
