# Generated by Django 3.0.6 on 2020-05-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20200517_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tree'),
        ),
    ]
