# Generated by Django 3.0.6 on 2020-05-22 01:59

from django.db import migrations
from django.db import models

def set_default_tree(apps, schema_editor):
    Entry = apps.get_model('tags', 'Entry')
    Tree = apps.get_model('tags', 'Tree')
    for entry in Entry.objects.all():
        entry.tree = Tree.objects.first()
        entry.save()

def rev_set_default_tree(apps, schema_editor):
    Entry = apps.get_model('tags', 'Entry')
    for entry in Entry.objects.all():
        entry.tree = None
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_entry_tree'),
    ]

    operations = [
            migrations.RunPython(set_default_tree, rev_set_default_tree),
    ]
