# Generated by Django 3.0.6 on 2020-05-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_auto_20200522_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tree'),
        ),
    ]
