# Generated by Django 3.0.6 on 2020-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0018_group_grouprole_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprole',
            name='name',
            field=models.CharField(default='role', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
