# Generated by Django 3.0.6 on 2020-06-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0020_auto_20200613_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupRole',
            new_name='Role',
        ),
    ]
