# Generated by Django 3.0.6 on 2020-06-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0021_auto_20200613_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='TreeUserGroup',
        ),
    ]
