# Generated by Django 3.0.6 on 2020-06-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0025_auto_20200613_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.TreeUserGroup'),
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.TreeUserGroup'),
        ),
        migrations.AddField(
            model_name='tree',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.TreeUserGroup'),
        ),
    ]
