# Generated by Django 3.0.6 on 2020-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0028_auto_20200613_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeusergroup',
            name='public_group',
            field=models.BooleanField(default=False),
        ),
    ]
