# Generated by Django 3.0.6 on 2020-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0029_treeusergroup_public_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeusergroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
