# Generated by Django 3.0.6 on 2020-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0030_auto_20200614_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeusergroup',
            name='listed_group',
            field=models.BooleanField(default=False),
        ),
    ]
