# Generated by Django 3.0.6 on 2020-06-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0035_auto_20200614_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.TreeUserGroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Role')),
            ],
        ),
    ]
