# Generated by Django 3.0.6 on 2020-06-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0036_memberinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberInvitation',
        ),
    ]
