# Generated by Django 3.0.6 on 2020-07-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0038_auto_20200630_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeusergroup',
            name='group_status',
            field=models.CharField(choices=[('PRIV', 'Private'), ('PUB', 'Unlisted and Public'), ('LIS', 'Listed and Public')], default='PRIV', max_length=4),
        ),
    ]
