# Generated by Django 3.0.6 on 2020-07-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0040_auto_20200704_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeusergroup',
            old_name='group_status',
            new_name='group_visibility',
        ),
    ]
