# Generated by Django 3.0.6 on 2020-07-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0041_auto_20200705_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeusergroup',
            name='listed_group',
        ),
        migrations.RemoveField(
            model_name='treeusergroup',
            name='public_group',
        ),
    ]
