# Generated by Django 3.0.6 on 2020-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0042_auto_20200705_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeusergroup',
            name='listed_to_public',
            field=models.CharField(choices=[('INV', 'Only invited users'), ('USR', 'Only users'), ('ALL', 'Everyone')], default='INV', max_length=3),
        ),
        migrations.AddField(
            model_name='treeusergroup',
            name='visible_to_public',
            field=models.CharField(choices=[('INV', 'Only invited users'), ('USR', 'Only users'), ('ALL', 'Everyone')], default='INV', max_length=3),
        ),
    ]
