# Generated by Django 3.0.6 on 2020-07-12 17:21

from django.db import migrations

def set_default_visibility(apps, schema_editor):

    TreeUserGroup = apps.get_model('tags', 'TreeUserGroup')

    for group in TreeUserGroup.objects.all():

        if group.group_visibility == 'PRIV':
            group.listed_to_public = 'INV'
            group.visible_to_public = 'INV'
        elif group.group_visibility == 'PUB':
            group.listed_to_public = 'INV'
            group.visible_to_public = 'USR'
        else:
            group.listed_to_public = 'USR'
            group.visible_to_public = 'USR'

def rev_set_default_visibility(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0043_auto_20200712_1921'),
    ]

    operations = [
        migrations.RunPython(set_default_visibility, rev_set_default_visibility),
    ]
