# Generated by Django 3.0.6 on 2020-07-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0044_auto_20200712_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeusergroup',
            name='group_visibility',
        ),
    ]
