# Generated by Django 3.0.6 on 2020-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0045_remove_treeusergroup_group_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='description',
            field=models.CharField(default='', max_length=2048, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tree',
            name='entry_display',
            field=models.CharField(choices=[('CPS', 'Compact (small)'), ('CPM', 'Compact (medium)'), ('CPL', 'Compact (large)'), ('LST', 'List')], default='CPL', max_length=3),
        ),
    ]
