# Generated by Django 3.0.6 on 2020-07-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0046_auto_20200717_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
