# Generated by Django 3.0.6 on 2020-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0048_auto_20200718_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en-us', max_length=10),
        ),
    ]
