# Generated by Django 3.0.6 on 2020-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0050_auto_20200725_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='fr', max_length=10),
        ),
    ]
