# Generated by Django 3.0.6 on 2020-07-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0051_auto_20200725_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
